# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='issuedticket',
            name='uid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
