# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Item in cart'), ('TICKET_ISSUED', 'Payment confirmed, ticket issued')], default='CREATED', max_length=25),
        ),
        migrations.AddField(
            model_name='cart',
            name='ticket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.IssuedTicket'),
        ),
    ]
