# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20160429_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Item in cart'), ('TICKET_ISSUED', 'Payment confirmed, ticket issued'), ('PAYMENT_FAILED', 'Payment failed'), ('PAYMENT_ERROR', 'Payment error'), ('SANDBOX_TICKET_ISSUED', 'Sandbox payment confirmed, ticket issued')], default='CREATED', max_length=25),
        ),
    ]
