# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20160430_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='lp_action',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_currency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_err_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_err_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_liqpay_order_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_payment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_paytype',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_public_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_sender_card_mask2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='lp_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Item in cart'), ('TICKET_ISSUED', 'Payment confirmed, ticket issued'), ('PAYMENT_FAILED', 'Payment failed')], default='CREATED', max_length=25),
        ),
    ]
