# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20160430_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqpaydata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
