# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_liqpaydata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='<noname>', max_length=200),
        ),
    ]
