# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20160524_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
