# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_cart_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='place',
            field=models.CharField(default='<no place>', max_length=400),
        ),
        migrations.AddField(
            model_name='campaign',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
