# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 14:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20160526_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='midname',
            field=models.CharField(default='<no midname>', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='cart',
            name='residence',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='surname',
            field=models.CharField(default='<no surname>', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='vk_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='working_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(default='<no name>', max_length=200),
        ),
    ]
