# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_auto_20160526_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='available_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='available_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
