# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20160527_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
