# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_auto_20160527_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='available_until',
            new_name='available_till',
        ),
    ]
