# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_auto_20160527_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedticket',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
