# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def move_amount_unlimited(apps, schema_editor):
    TicketType = apps.get_model("campaigns", "TicketType")
    TicketCounter = apps.get_model("campaigns", "TicketCounter")
    for row in TicketType.objects.all():
        ticket_counter = TicketCounter(amount=row.amount,
                                       unlimited=row.unlimited,
                                       campaign=row.campaign)
        ticket_counter.save()
        row.counter = ticket_counter
        row.save()


def reverse_move_amount_unlimited(apps, schema_editor):
    TicketType = apps.get_model("campaigns", "TicketType")
    for row in TicketType.objects.all():
        if row.counter:
            row.amount = row.counter.amount
            row.unlimited = row.counter.unlimited
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_issuedticket_checked_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unlimited', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='tickettype',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.TicketCounter'),
        ),
        migrations.RunPython(move_amount_unlimited, reverse_code=reverse_move_amount_unlimited),
        migrations.RemoveField(
            model_name='tickettype',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='unlimited',
        ),
    ]
