# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Cart'),
        ),
    ]
